import argparse
from enum import Enum
import numpy as np

from svgpathtools import svg2paths

import cglib.fdm_aa
import cglib.polyline


def compute_extrusion_length(width: float,
            local_length: float,
            filament_diameter: float,
            layer_height: float,
            flow_multiplier: float) -> float:
    """Compute the length of the filament to extrude.
    
    Notes
    -----
    https://3dprinting.stackexchange.com/questions/6289/how-is-the-e-argument-calculated-for-a-given-g1-command
    """
    crsec = np.pi * filament_diameter**2 / 4.0
    v_mm3 = local_length * layer_height * width
    return flow_multiplier * v_mm3 / crsec


def features_get_bed_size_xy(features_str: str) -> np.ndarray:

    bed_circular = features_str.find("bed_circular  = true") != -1
    bed_circular = bed_circular or features_str.find("bed_circular = true") != -1
    if not bed_circular:
        # The bed is not circular

        features_bed_size_x_i = features_str.find("bed_size_x_mm")
        bed_size_x = features_str[features_bed_size_x_i:]
        bed_size_x_i_end = bed_size_x.find('\n')
        bed_size_x = bed_size_x[:bed_size_x_i_end]
        bed_size_x = float(bed_size_x.split()[2])

        features_bed_size_y_i = features_str.find("bed_size_y_mm")
        bed_size_y = features_str[features_bed_size_y_i:]
        bed_size_y_i_end = bed_size_y.find('\n')
        bed_size_y = bed_size_y[:bed_size_y_i_end]
        bed_size_y = float(bed_size_y.split()[2])

        return np.array([bed_size_x, bed_size_y])
    else:

        bed_radius = features_str.find("bed_radius")
        bed_radius = features_str[bed_radius:]
        bed_radius_i_end = bed_radius.find('\n')
        bed_radius = bed_radius[:bed_radius_i_end]
        bed_radius = float(bed_radius.split()[2])

        return np.array([bed_radius, bed_radius]) * 2.


def features_origin_is_bed_center(features_str: str) -> np.ndarray:
    origin_is_bed_center = False
    index = features_str.find("bed_origin_x = bed_size_x_mm / 2.0")
    origin_is_bed_center = index != -1 or origin_is_bed_center
    index = features_str.find("bed_origin_x = bed_size_x_mm/2")
    origin_is_bed_center = index != -1 or origin_is_bed_center

    return origin_is_bed_center


def run():
    parser = argparse.ArgumentParser(
        description='Convert the cycle generated by fill_2d_shape.py to machine instructions. Input: The JSON file used by fill_2d_shape.py. Output: The G-code to print the generated cycle.'
    )
    parser.add_argument(
        "input_filename", help="The JSON file used by fill_2d_shape.py.")
    parser.add_argument(
        "printer_profile", help="The printer profile. Only 'CR10S_Pro' was tested. In theory, the name of the folders at `src/ext/iceslprinters/fff` are valid inputs.")
    parser.add_argument(
        "-nw",
        "--nozzle_width",
        help="The nozzle diameter in millimeter. Default: the nozzle width in the input file.",
        type=float)
    parser.add_argument(
        "-s",
        "--speed",
        help="The speed of the moving head, in mm/s. Default: 30.",
        type=float,
        default=30.)
    parser.add_argument(
        "-fm",
        "--flow_multiplier",
        help="The flow multiplier. Default: 1",
        type=float,
        default=1.0)
    parser.add_argument(
        "-lc",
        "--layer_count",
        help="The number of layers. Default 3.",
        type=int,
        default=3)
    parser.add_argument(
        "-bt",
        "--bed_temp",
        help="The bed temperature in degree Celsius. Default: 55.",
        type=int,
        default=55)
    parser.add_argument(
        "-et",
        "--extruder_temp",
        help="The extruder temperature in degree Celsius. Default: 215.",
        type=int,
        default=215)
    parser.add_argument(
        "-lh",
        "--layer_height",
        help="The layer height. Default: the layer height associated with the polyline.",
        type=float)
    parser.add_argument(
        "-fd",
        "--filament_diameter",
        help="The filament diameter of the filament used by the printer. Default: 1.75 mm.",
        type=float,
        default=1.75)
    
    args = parser.parse_args()

    input_param_filename = args.input_filename
    printer_profile = args.printer_profile

    nozzle_width = args.nozzle_width
    speed = args.speed
    flow_multiplier = args.flow_multiplier
    layer_count = args.layer_count
    bed_temp = args.bed_temp
    extruder_temp = args.extruder_temp
    layer_height = args.layer_height
    filament_diameter = args.filament_diameter

    parameters = cglib.fdm_aa.Parameters()
    parameters.load(input_param_filename)

    # Load svg paths
    # Transformations inside the SVG are ignored, so only SVG files without
    # transformations are valid. Using Inkscape, ensure your contour is not
    # associated with a layer to avoid implicit transformations. Be sure that
    # the contour is a clockwise-oriented closed polyline. Holes are
    # represented with counter-clockwise oriented closed polylines.
    _, _, svg_attributes = svg2paths(
        parameters.svg_path, return_svg_attributes=True)
    # The shape domain size is determined by the SVG width and heigh
    # -2: remove the unit
    object_width_x = float(svg_attributes['width'][:-2])
    object_width_y = float(svg_attributes['height'][:-2])
    object_width_xy = np.array([object_width_x, object_width_y])

    # If the user does not specify the nozzle width,
    # use by default the one in the input file
    if nozzle_width is None:
        nozzle_width = parameters.nozzle_width

    cycle_polyline = cglib.polyline.load(parameters.cycle_polyline_filename)
    if layer_height is None:
        layer_height = cycle_polyline.data[0, 1]

    gcode_filename = parameters.gcode_filename

    # Get the printer profile header and footer
    printer_profile_path_head = f"src/ext/iceslprinters/fff/{printer_profile}/"
    printer_profile_header_path = printer_profile_path_head + "header.gcode"
    printer_profile_footer_path = printer_profile_path_head + "footer.gcode"
    printer_profile_features_path = printer_profile_path_head + "features.lua"
    printer_profile_printer_path = printer_profile_path_head + "printer.lua"

    # File to string
    with open(printer_profile_header_path, 'r') as f:
        header_str = f.read()
    with open(printer_profile_footer_path, 'r') as f:
        footer_str = f.read()
    with open(printer_profile_features_path, 'r') as f:
        features_str = f.read()
    with open(printer_profile_printer_path, 'r') as f:
        printer_str = f.read()

    # Extract the bed size from features string
    bed_size_xy = features_get_bed_size_xy(features_str)
    origin_is_bed_center = features_origin_is_bed_center(printer_str)

    # Put user defined parameters in the header
    header_str = header_str.replace("<HBPTEMP>", str(int(bed_temp)))
    header_str = header_str.replace("<TOOLTEMP>", str(int(extruder_temp)))
    header_str = header_str.replace("<BEDLVL>", "G0 F6200 X0 Y0")

    # mm/s to mm/min
    feedrate = int(speed * 60.)
    # Total extrusion length
    total_extrusion_length = 0.0

    world_to_object = -object_width_xy*0.5
    if origin_is_bed_center:
        object_to_bed = np.array([0., 0.])
    else:
        # Assume left-bottom origin
        object_to_bed = bed_size_xy*0.5

    with open(gcode_filename, 'w', encoding="utf-8") as f:
        # Write header
        f.write(header_str)

        # Write the same cycle for each layer
        cycle_polyline_2dpoint: np.ndarray = cycle_polyline.point[0]
        cycle_radius: np.ndarray = cycle_polyline.point_data[0]
        for layer_index in range(layer_count):
            layer_height_i = (layer_index + 1) * layer_height
            layer_height_i_str = f"{layer_height_i:.6f}"
            for point_index in range(cycle_polyline_2dpoint.shape[0]):
                point_i = cycle_polyline_2dpoint[point_index]
                point_i = point_i + world_to_object + object_to_bed
                point_x_str = f"{point_i[0]:.3f}"
                point_y_str = f"{point_i[1]:.3f}"
                width_i = cycle_radius[point_index] * 2.
                if point_index == 0:
                    f.write(f"G0 F{feedrate} X{point_x_str} Y{point_y_str} Z{layer_height_i_str}\n")
                else:
                    point_im1 = cycle_polyline_2dpoint[point_index-1]
                    point_im1 = point_im1 + world_to_object + object_to_bed
                    dist_pi_im1 = np.linalg.norm(point_i - point_im1)
                    width_im1 = cycle_radius[point_index-1] * 2.
                    width_i = (width_im1 + width_i) * 0.5
                    extrusion_length = compute_extrusion_length(
                        width_i,
                        dist_pi_im1,
                        filament_diameter,
                        layer_height,
                        flow_multiplier)
                    total_extrusion_length += extrusion_length
                    total_extrusion_length_str = f"{total_extrusion_length:.6f}"
                    f.write(f"G1 F{feedrate} X{point_x_str} Y{point_y_str} Z{layer_height_i_str} E{total_extrusion_length_str}\n")
        
        # Write footer
        f.write(footer_str)


if __name__ == "__main__":
    run()
